features/greeting_a_customer.feature
src/Controller/GreetingController.php
src/Resources/config/app/shop_routing.yml
tests/Application/app/config/routing.yml
tests/Behat/Context/Ui/Shop/WelcomeContext.php
tests/Behat/Page/Shop/WelcomePage.php
tests/Behat/Page/Shop/WelcomePageInterface.php
tests/Behat/Resources/services.xml
tests/Behat/Resources/suites.yml

Greeting a customer

---

.travis.yml
node_modules
src/Controller/GreetingController.php
src/Resources/public/greeting.js
src/Resources/views/dynamic_greeting.html.twig
tests/Application/.gitignore
tests/Application/Gulpfile.js
tests/Application/package.json

Using symbolic links to fix `node_modules`.

Handle assets in test environment

---

.travis.yml
composer.json
src/Controller/GreetingController.php
src/DependencyInjection/AcmeExampleExtension.php
src/DependencyInjection/Configuration.php
tests/Application/app/AppKernel.php
tests/Behat/Context/Ui/Shop/WelcomeContext.php
tests/Behat/Page/Shop/DynamicWelcomePage.php
tests/Behat/Page/Shop/StaticWelcomePage.php
tests/Behat/Page/Shop/WelcomePageInterface.php

As PHP 7.1 is now the only PHP version supported by **Sylius**, it should be here as well.

Use PHP 7.1

---

.travis.yml
behat.yml.dist
src/Controller/GreetingController.php
src/Resources/views/static_greeting.html.twig

Run Javascript scenarios & use Yarn

---

tests/Application/.gitignore
tests/Application/web/app_dev.php

Fixes #29, closes #41 (which fixes #32).

Add development environment

---

tests/Application/app/AppKernel.php
tests/Application/app/config/config.yml

Move cache & logs to a temporary directory

---

README.md

Centered logo and repository title with badges

Make readme look like Sylius one

---

.travis.yml
features/running_a_sylius_feature.feature
tests/Application/Gulpfile.js

Run a Sylius scenario to see whether JS is loading correctly

---

README.md

Make badges great again

---

.gitignore
.travis.yml
README.md
composer.json

README fixes + move Composer binaries

---

composer.json
phpspec.yml.dist
phpunit.xml.dist
src/AcmeSyliusExamplePlugin.php
src/Controller/GreetingController.php
src/DependencyInjection/AcmeSyliusExampleExtension.php
src/DependencyInjection/Configuration.php
src/Resources/config/app/shop_routing.yml
src/Resources/views/dynamic_greeting.html.twig
tests/Application/app/AppKernel.php
tests/Application/app/config/routing.yml
tests/Behat/Context/Ui/Shop/WelcomeContext.php
tests/Behat/Page/Shop/DynamicWelcomePage.php
tests/Behat/Page/Shop/StaticWelcomePage.php
tests/Behat/Page/Shop/WelcomePageInterface.php
tests/Behat/Resources/services.xml
tests/Behat/Resources/suites.yml

Related to Sylius/Sylius#8903.

Follow new naming convention

---

.travis.yml

https://bugs.chromium.org/p/chromedriver/issues/detail?id=1950

Upgrade to Chromedriver 2.35 to get around Network.DeleteCookie error

---

.gitignore
.travis.yml
tests/Application/.gitignore
tests/Application/package.json

Closes #80, closes #79, closes #77, closes #75, closes #73.
Thanks @stefandoorn and @lsmith77 🎉

Aggregate proposed fixes & make Travis passing again

---

tests/Application/app/AppKernel.php

Rebased #66 by @bitbager.
Fixes #60, closes #66.

Save cache and logs in project directory

---

tests/Application/app/config/config.yml
tests/Application/app/config/config_prod.yml

Rebased #71 by @bitbager.
Fixes #70, closes #71.

Enable monolog

---

tests/Application/.gitignore

Proper gitignore for 1.1 branch

---

tests/Application/app/AppKernel.php
tests/Application/app/config/config_dev.yml
tests/Application/app/config/routing_dev.yml

Currently the you can't debug the plugin while developing it with the build-in application.

Added dev mode to the plugin skeleton

---

.travis.yml
composer.json
phpstan.neon

Bring more PHPStan power to the skeleton!

---

tests/Application/.gitignore

Getting rid of `Root image path not resolvable "/Users/pamil/Projects/Sylius/InvoicingPlugin/tests/Application/web/media/image”` error.

Keep predefined directories in "web" in test application

---

.gitignore
tests/Application/.gitignore

Same as #117, it follows Symfony conventions from official recipes.

Rename ".gitkeep" to ".gitignore"

---

composer.json

Bring back "sylius-plugin" package type

---

composer.json
tests/Application/.gitignore

Fixes the issue with unexistent security checker & missing `public/media/image` directory.

Miscellaneous fixes for 1.3

---

UPGRADE-1.3.md

Fix links to diffs mentioned in UPGRADE file

---

tests/Application/app/config/config.yml

https://github.com/Sylius/Sylius/issues/9554

Do not send admin notifications from plugin tests

---

composer.json

Related **Sylius** PR: https://github.com/Sylius/Sylius/pull/9970

Fix 1.2 build

---

tests/Application/config/packages/security.yaml

Related PR https://github.com/Sylius/Sylius/pull/10008

Incorporate changes about password encoder

---

.travis.yml
tests/Application/Kernel.php

changes incorporated from https://github.com/Sylius/Sylius/pull/10067

Remove container cleanup in test environment (1.3)

---

UPGRADE-1.4.md

Based on 1.4 upgrade done in this PR: https://github.com/Sylius/CustomerOrderCancellationPlugin/pull/16.

Make UPGRADE-1.4 even better

---

.travis.yml

According to the JSON schema these values are strings

Fixing validation against json schema

---

UPGRADE-1.4.md

Added information on modifying the kernel of the test application to match the new version.

Information about modifying the Kernel when upgrading to version 1.4

---

tests/Application/.env

update server version to 5.7 to avoid json database errors

update server version

---

.github/workflows/build.yml
.gitignore
tests/Application/config/packages/_sylius.yaml
tests/Application/config/packages/api_platform.yaml
tests/Application/config/packages/fos_rest.yaml
tests/Application/config/packages/framework.yaml
tests/Application/config/packages/security.yaml

Fix and enable the API in test app.

Fix test app API

---

.github/workflows/build.yml

[Maintenance] Support PHP 8.1

---

ecs.php

Update ecs from ContainerConfigurator to ECSConfig syntax

Update ecs syntax
